_name: grace
n_iter: 5
eps: 1.0  # 初始化的 init_epsilon
dist_fn: euc # euc, mmd, cos
val_init: cold # cold, warm
val_train: sgd # sgd, pert
val_reg: None # early
reg: early_stop # early_stop
replacement: replace_prompt # replace_last, replace_all, replace_prompt
eps_expand: coverage # , moving_avg, decay
num_pert: 8 # only matters when using perturbation training
inner_params:
- encoder.block[4].layer[1].DenseReluDense.wo.weight  #